version: '3'
services:
  frontend:
    build: ./frontend
    container_name: affiliates_frontend
    ports:
      - 5173:5173

  backend:
    build: ./backend
    container_name: affiliates_backend
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: affiliates_db
    networks:
      - app-network

  database:
    image: mysql:latest
    container_name: affiliates_db
    restart: always 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: affiliates_db
    volumes:
      - ./.docker/data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
